@startuml
!include ../style.puml

Actor User as user USER_COLOR
box Ui UI_COLOR_T1
Participant ":UI" as ui UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ShowTagCommandParser" as ShowTagCommandParser LOGIC_COLOR
participant "s:ShowTagContactCommand" as ShowTagContactCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
Participant ":Storage" as Storage STORAGE_COLOR
end box

user -[USER_COLOR]> ui : "show contact t/CS2100Teammate"
activate ui UI_COLOR

ui -[UI_COLOR]> LogicManager : execute("show ...")
activate LogicManager LOGIC_COLOR

LogicManager -[LOGIC_COLOR]> AddressBookParser : parseCommand("show ...")
activate AddressBookParser LOGIC_COLOR

create ShowTagCommandParser
AddressBookParser -[LOGIC_COLOR]> ShowTagCommandParser
activate ShowTagCommandParser LOGIC_COLOR

ShowTagCommandParser -[LOGIC_COLOR]-> AddressBookParser
deactivate ShowTagCommandParser


AddressBookParser -[LOGIC_COLOR]> ShowTagCommandParser : parse("contact t/CS2100Teammate")
activate ShowTagCommandParser LOGIC_COLOR

create ShowTagContactCommand
ShowTagCommandParser -[LOGIC_COLOR]> ShowTagContactCommand
activate ShowTagContactCommand LOGIC_COLOR

ShowTagContactCommand -[LOGIC_COLOR]-> ShowTagCommandParser : s
deactivate ShowTagContactCommand

ShowTagCommandParser -[LOGIC_COLOR]-> AddressBookParser : s
deactivate ShowTagCommandParser

ShowTagCommandParser -[hidden]-> AddressBookParser
destroy ShowTagCommandParser


AddressBookParser -[LOGIC_COLOR]-> LogicManager : s
deactivate AddressBookParser

LogicManager -[LOGIC_COLOR]> ShowTagContactCommand : execute()
activate ShowTagContactCommand LOGIC_COLOR

ShowTagContactCommand -[LOGIC_COLOR]> Model : updateFilteredPersonList(predicate)
activate Model MODEL_COLOR

Model -[MODEL_COLOR]-> ShowTagContactCommand
deactivate Model

group ref save file
LogicManager -[hidden]-> Storage
end group

create CommandResult
ShowTagContactCommand -[LOGIC_COLOR]> CommandResult
activate CommandResult LOGIC_COLOR

CommandResult -[LOGIC_COLOR]-> ShowTagContactCommand
deactivate CommandResult
CommandResult -[hidden]-> ShowTagContactCommand
destroy CommandResult

ShowTagContactCommand -[LOGIC_COLOR]-> LogicManager : result
deactivate ShowTagContactCommand

ShowTagContactCommand -[hidden]-> ShowTagCommandParser
destroy ShowTagContactCommand

ui <-[LOGIC_COLOR]-LogicManager : result
deactivate LogicManager

user <-[UI_COLOR]-ui : result
deactivate ui
@enduml
