@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

abstract class "{abstract}\nCommand" as Command
class DueBeforeCommand
class DueByCommand

Command <|-- DueBeforeCommand
Command <|-- DueByCommand

@enduml
