@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

interface Parser <<Interface>>
class DueBeforeCommandParser
class DueAtCommandParser

Parser <|.. DueBeforeCommandParser
Parser <|.. DueAtCommandParser

@enduml
