@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

interface "Parser<FindCommand>" <<Interface>>
class FindCommandParser

"Parser<FindCommand>" <|.. FindCommandParser

@enduml
