@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR



note right of AbcStorage
""Abc"" = ""TaskList"",
""UserPrefs"", ""AddressBook""
end note
note right of JsonAbcStorage
""Abc"" = ""TaskList"",
""UserPrefs"", ""AddressBook""
end note
Class Storage <<Interface>>
Class UserPrefsStorage <<Interface>>
Class AbcStorage <<Interface>>
Class StorageManager
Class JsonUserPrefsStorage
Class JsonAbcStorage


StorageManager .up.|> Storage
StorageManager o-left> UserPrefsStorage
StorageManager o-right> AbcStorage
JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAbcStorage .up.|> AbcStorage
@enduml
