@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

interface "Predicate<Task>" <<Interface>>
class TaskMatchesFindKeywordPredicate

"Predicate<Task>" <|.. TaskMatchesFindKeywordPredicate

@enduml
